[project]
name = "lm-from-scratch"
version = "0.1.0"
description = "My implementation of Language modeling from scratch"
requires-python = ">=3.10"
dependecies = [
        "torch",
        "tqdm"
]


[build-system]

requires = ["setuptools","wheel"]
build-backend = "setuptools.build_meta"
